[profile.default]
src = "src"
out = "out"
dotenv = true
libs = ["lib"]

[rpc_endpoints]
amoy = "${AMOY_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

[etherscan]
amoy = { key = "${POLYGONSCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
